---
# Motors control
- ros_topic_name: "/fmu/in/actuator_motors"
  gz_topic_name: "/model/x500_lidar_2d_0/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ

# IMU Data
- ros_topic_name: "/fmu/out/sensor_combined"
  gz_topic_name: "/world/iris_maze/model/x500_lidar_2d_0/link/base_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Vehicle Odometry
- ros_topic_name: "/fmu/out/vehicle_odometry"
  gz_topic_name: "/model/x500_lidar_2d_0/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS

# Distance/Lidar Sensor
- ros_topic_name: "/fmu/in/obstacle_distance"
  gz_topic_name: "/world/iris_maze/model/x500_lidar_2d_0/link/link/sensor/lidar_2d_v2/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Clock sync
- ros_topic_name: "/parameter_events"
  gz_topic_name: "/world/iris_maze/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# GPS/NavSat
- ros_topic_name: "/fmu/out/vehicle_gps_position"
  gz_topic_name: "/world/iris_maze/model/x500_lidar_2d_0/link/base_link/sensor/navsat_sensor/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# Air Pressure
- ros_topic_name: "/fmu/out/sensor_combined"
  gz_topic_name: "/world/iris_maze/model/x500_lidar_2d_0/link/base_link/sensor/air_pressure_sensor/air_pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS

# Airspeed
- ros_topic_name: "/fmu/out/sensor_combined"
  gz_topic_name: "/world/iris_maze/model/x500_lidar_2d_0/link/airspeed_link/sensor/air_speed/air_speed"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS



# ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=$WORKSPACE/home/shibin/ws_sensor_combined/src/rrt_package/config/px4_gz_bridge.yaml
